### ISSUE TITLE
Unable to login: Please provide guidance on how to create Firebase database.

### ISSUE THREAD

**Issue by ashish141199** [dharan1011/CollegeConnect#1]
Great code. But I am not getting how to create a database for the backend. Unable to login. Help needed.

**Comment by dharanad** [comment]
You need create a firebase project and connect this app to the project. https://firebase.google.com/docs/android/setup
refer the docs, that might help. If not fixed i will help you further.

**Comment by ashish141199** [comment]
Thank you @dharan1011 for your quick reply. Will let you know in some time
